version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: paytech
      POSTGRES_PASSWORD: paytech
      POSTGRES_DB: paytech_checkout
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}
